language: node_js
node_js:
- '8.9.1'
before_install:
- export DISPLAY=:99.0
install:
- npm install
script:
- node_modules/.bin/grunt build --dist
- npm test
notifications:
  slack: universalviewer:0hPpv56Z7ber0j0C6KdLwFFW
